M48
; DRILL file {KiCad 9.0.7} date 2026-03-18T14:01:15+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-18T14:01:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.300
%
G90
G05
T1
X54.0Y-26.0
X54.0Y-72.0
X100.0Y-26.0
X100.0Y-72.0
M30
